variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Azure service connection>'
    appType: 'webAppLinux'
    appName: '<Name of web app>'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(0ea62a50-7130-4a99-920f-af4634666615)'
    appType: 'webAppLinux'
    appName: 'conan0h.Cloud-Computing-Lab-5'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'