variables:
  buildConfiguration: 'Release'

steps:
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure for Students(0ea62a50-7130-4a99-920f-af4634666615)'
    appType: 'functionApp'
    appName: 'cloudComputingLab5'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(0ea62a50-7130-4a99-920f-af4634666615)'
    appType: 'webAppLinux'
    appName: 'conan0h.Cloud-Computing-Lab-5'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'